import { config as defaultConfig } from '@gluestack-ui/themed';
import { tokens } from './src/ui/tokens';

export const config = {
  ...defaultConfig,
  tokens: {
    colors: {
      primary50: tokens.colors.primary[50],
      primary100: tokens.colors.primary[100],
      primary200: tokens.colors.primary[200],
      primary300: tokens.colors.primary[300],
      primary400: tokens.colors.primary[400],
      primary500: tokens.colors.primary[500],
      primary600: tokens.colors.primary[600],
      primary700: tokens.colors.primary[700],
      primary800: tokens.colors.primary[800],
      primary900: tokens.colors.primary[900],

      secondary50: tokens.colors.secondary[50],
      secondary100: tokens.colors.secondary[100],
      secondary200: tokens.colors.secondary[200],
      secondary300: tokens.colors.secondary[300],
      secondary400: tokens.colors.secondary[400],
      secondary500: tokens.colors.secondary[500],
      secondary600: tokens.colors.secondary[600],
      secondary700: tokens.colors.secondary[700],
      secondary800: tokens.colors.secondary[800],
      secondary900: tokens.colors.secondary[900],

      success50: tokens.colors.success[50],
      success100: tokens.colors.success[100],
      success200: tokens.colors.success[200],
      success300: tokens.colors.success[300],
      success400: tokens.colors.success[400],
      success500: tokens.colors.success[500],
      success600: tokens.colors.success[600],
      success700: tokens.colors.success[700],
      success800: tokens.colors.success[800],
      success900: tokens.colors.success[900],

      error50: tokens.colors.error[50],
      error100: tokens.colors.error[100],
      error200: tokens.colors.error[200],
      error300: tokens.colors.error[300],
      error400: tokens.colors.error[400],
      error500: tokens.colors.error[500],
      error600: tokens.colors.error[600],
      error700: tokens.colors.error[700],
      error800: tokens.colors.error[800],
      error900: tokens.colors.error[900],

      warning50: tokens.colors.warning[50],
      warning100: tokens.colors.warning[100],
      warning200: tokens.colors.warning[200],
      warning300: tokens.colors.warning[300],
      warning400: tokens.colors.warning[400],
      warning500: tokens.colors.warning[500],
      warning600: tokens.colors.warning[600],
      warning700: tokens.colors.warning[700],
      warning800: tokens.colors.warning[800],
      warning900: tokens.colors.warning[900],

      info50: tokens.colors.info[50],
      info100: tokens.colors.info[100],
      info200: tokens.colors.info[200],
      info300: tokens.colors.info[300],
      info400: tokens.colors.info[400],
      info500: tokens.colors.info[500],
      info600: tokens.colors.info[600],
      info700: tokens.colors.info[700],
      info800: tokens.colors.info[800],
      info900: tokens.colors.info[900],

      neutral50: tokens.colors.neutral[50],
      neutral100: tokens.colors.neutral[100],
      neutral200: tokens.colors.neutral[200],
      neutral300: tokens.colors.neutral[300],
      neutral400: tokens.colors.neutral[400],
      neutral500: tokens.colors.neutral[500],
      neutral600: tokens.colors.neutral[600],
      neutral700: tokens.colors.neutral[700],
      neutral800: tokens.colors.neutral[800],
      neutral900: tokens.colors.neutral[900],
      neutral950: tokens.colors.neutral[950],
    },
    space: {
      0: tokens.spacing[0],
      1: tokens.spacing[1],
      2: tokens.spacing[2],
      3: tokens.spacing[3],
      4: tokens.spacing[4],
      5: tokens.spacing[5],
      6: tokens.spacing[6],
      8: tokens.spacing[8],
      10: tokens.spacing[10],
      12: tokens.spacing[12],
      16: tokens.spacing[16],
      20: tokens.spacing[20],
      24: tokens.spacing[24],
      32: tokens.spacing[32],
    },
    fontSizes: {
      xs: tokens.typography.fontSize.xs,
      sm: tokens.typography.fontSize.sm,
      base: tokens.typography.fontSize.base,
      lg: tokens.typography.fontSize.lg,
      xl: tokens.typography.fontSize.xl,
      '2xl': tokens.typography.fontSize['2xl'],
      '3xl': tokens.typography.fontSize['3xl'],
      '4xl': tokens.typography.fontSize['4xl'],
      '5xl': tokens.typography.fontSize['5xl'],
      '6xl': tokens.typography.fontSize['6xl'],
    },
    fonts: {
      sans: tokens.typography.fontFamily.sans,
      mono: tokens.typography.fontFamily.mono,
    },
    fontWeights: {
      normal: tokens.typography.fontWeight.normal,
      medium: tokens.typography.fontWeight.medium,
      semibold: tokens.typography.fontWeight.semibold,
      bold: tokens.typography.fontWeight.bold,
    },
    lineHeights: {
      tight: tokens.typography.lineHeight.tight,
      normal: tokens.typography.lineHeight.normal,
      relaxed: tokens.typography.lineHeight.relaxed,
    },
    letterSpacings: {
      tighter: tokens.typography.letterSpacing.tighter,
      tight: tokens.typography.letterSpacing.tight,
      normal: tokens.typography.letterSpacing.normal,
      wide: tokens.typography.letterSpacing.wide,
      wider: tokens.typography.letterSpacing.wider,
      widest: tokens.typography.letterSpacing.widest,
    },
    radii: {
      none: tokens.spacing.borderRadius.none,
      sm: tokens.spacing.borderRadius.sm,
      base: tokens.spacing.borderRadius.base,
      md: tokens.spacing.borderRadius.md,
      lg: tokens.spacing.borderRadius.lg,
      xl: tokens.spacing.borderRadius.xl,
      full: tokens.spacing.borderRadius.full,
    },
  },
};

export default config;
