/** @type {import('tailwindcss').Config} */
const tokens = require('./src/ui/tokens.json');

module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        primary: tokens.colors.primary,
        secondary: tokens.colors.secondary,
        success: tokens.colors.success,
        error: tokens.colors.error,
        warning: tokens.colors.warning,
        info: tokens.colors.info,
        neutral: tokens.colors.neutral,
        text: tokens.colors.text,
        background: tokens.colors.background,
        surface: tokens.colors.surface,
        border: tokens.colors.border,
        code: tokens.colors.code,
      },
      spacing: {
        0: `${tokens.spacing[0]}px`,
        1: `${tokens.spacing[1]}px`,
        2: `${tokens.spacing[2]}px`,
        3: `${tokens.spacing[3]}px`,
        4: `${tokens.spacing[4]}px`,
        5: `${tokens.spacing[5]}px`,
        6: `${tokens.spacing[6]}px`,
        8: `${tokens.spacing[8]}px`,
        10: `${tokens.spacing[10]}px`,
        12: `${tokens.spacing[12]}px`,
        16: `${tokens.spacing[16]}px`,
        20: `${tokens.spacing[20]}px`,
        24: `${tokens.spacing[24]}px`,
        32: `${tokens.spacing[32]}px`,
      },
      fontFamily: {
        sans: [tokens.typography.fontFamily.sans],
        mono: [tokens.typography.fontFamily.mono],
      },
      fontSize: {
        xs: [`${tokens.typography.fontSize.xs}px`],
        sm: [`${tokens.typography.fontSize.sm}px`],
        base: [`${tokens.typography.fontSize.base}px`],
        lg: [`${tokens.typography.fontSize.lg}px`],
        xl: [`${tokens.typography.fontSize.xl}px`],
        '2xl': [`${tokens.typography.fontSize['2xl']}px`],
        '3xl': [`${tokens.typography.fontSize['3xl']}px`],
        '4xl': [`${tokens.typography.fontSize['4xl']}px`],
        '5xl': [`${tokens.typography.fontSize['5xl']}px`],
        '6xl': [`${tokens.typography.fontSize['6xl']}px`],
      },
      fontWeight: tokens.typography.fontWeight,
      lineHeight: tokens.typography.lineHeight,
      letterSpacing: tokens.typography.letterSpacing,
      borderRadius: {
        none: `${tokens.spacing.borderRadius.none}px`,
        sm: `${tokens.spacing.borderRadius.sm}px`,
        base: `${tokens.spacing.borderRadius.base}px`,
        md: `${tokens.spacing.borderRadius.md}px`,
        lg: `${tokens.spacing.borderRadius.lg}px`,
        xl: `${tokens.spacing.borderRadius.xl}px`,
        full: `${tokens.spacing.borderRadius.full}px`,
      },
      transitionDuration: {
        instant: `${tokens.motion.duration.instant}ms`,
        fast: `${tokens.motion.duration.fast}ms`,
        base: `${tokens.motion.duration.base}ms`,
        medium: `${tokens.motion.duration.medium}ms`,
        slow: `${tokens.motion.duration.slow}ms`,
        slower: `${tokens.motion.duration.slower}ms`,
      },
      transitionTimingFunction: tokens.motion.easing,
    },
  },
  plugins: [],
}

